version: "3.9"

services:

  test:
    image: ghcr.io/andrejvysny/rpwa-template:latest
    ports:
      - 80:80

    environment:
      - VITE_TITLE=MY_APP_TITLE
      - VITE_SUB_TITLE=MY_APP_SUB_TITLE
      - VITE_ENVIRONMENT=MY_APP_ENVIRONMENT


  app:
    container_name: app
    image: rpwa/app
    build:
      context: .
      target: development
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/var/www
      - ./var/www/node_modules
    ports:
      - "3000:3000"